// react-app/src/Login/Login.js
import React from "react";
import { Redirect } from "react-router-dom";
import { apiClient } from "../services/api";

const Login = (props) => {
  const [email, setEmail] = React.useState("");
  const [password, setPassword] = React.useState("");
  const [redirectToHome, setRedirectToHome] = React.useState(false);
  const [authError, setAuthError] = React.useState(false);

  const handleSubmit = (event) => {
    event.preventDefault();

    setAuthError(false);

    apiClient
      .post("api/login", {
        username: email,
        password: password,
      })
      .then((response) => {
        if (response.status === 200) {
          props.login(response.data);
          setRedirectToHome(true);
        }
      })
      .catch((error) => {
        if (error.response) {
          setAuthError(error.response.data);
        } else {
          setAuthError("Server is not connected, please try again later.");
        }
      });
  };

  if (redirectToHome === true) {
    return <Redirect to="/" />;
  }

  return (
    <div className="container login_container">
      <div className="card">
        <div className="card-header">
          <strong>Login</strong>
        </div>
        <div className="card-body">
          {authError ? (
            <div className="alert alert-danger">{authError}</div>
          ) : null}
          <form onSubmit={handleSubmit}>
            <div className="form-group">
              <label>Email</label>
              <input
                name="email"
                type="email"
                value={email}
                className={"form-control" + (authError ? " is-invalid" : "")}
                placeholder="Input your email..."
                onChange={(e) => setEmail(e.target.value)}
                required
              />
            </div>
            <div className="form-group">
              <label>Password</label>
              <input
                name="password"
                type="password"
                value={password}
                className={"form-control" + (authError ? " is-invalid" : "")}
                placeholder="Input your password..."
                onChange={(e) => setPassword(e.target.value)}
                required
              />
            </div>
            <button type="submit" className="btn btn-primary">
              Login
            </button>
          </form>
        </div>
      </div>
    </div>
  );
};

export default Login;

// frontend/src/views/auth/Login.vue
<template>
  <div class="container login_form">
    <div class="card">
      <div class="card-header">
        <strong>Login</strong>
      </div>
      <div class="card-body">
        <form @submit.prevent="login">
          <div class="alert alert-danger" v-if="error">
            {{ error }}
          </div>

          <div class="mb-3">
            <label>Email address</label>
            <input
              type="email"
              class="form-control"
              v-model="details.username"
            />
          </div>
          <div class="mb-3">
            <label>Password</label>
            <input
              type="password"
              class="form-control"
              v-model="details.password"
            />
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
  </div>
</template>

<script>
import { mapActions, mapGetters } from "vuex";

export default {
  name: "Login",

  data() {
    return {
      details: {
        username: "",
        password: ""
      }
    };
  },

  methods: {
    ...mapActions(["setError"]),

    login() {
      const formData = {
        username: this.details.username,
        password: this.details.password
      };
      this.$store.dispatch("login", formData).then(response => {
        if (response.data.access_token) {
          this.$router.push({ name: "Home" });
        }
      });
    }
  },

  computed: {
    ...mapGetters({
      error: "getError"
    })
  },

  mounted() {
    this.$store.commit("setError", null);
  }
};
</script>
