// frontend/src/views/Home.vue
<template>
  <div class="container">
    <div class="card">
      <div class="card-header">
        <strong>Home page</strong>
      </div>
      <div class="card-body">
        Content
        <div v-if="!getLoggedIn">
          You are need to logged_in
        </div>
        <div v-else>
          Hello {{ getUser.name }}, you are
          <span v-if="getUser.is_admin == true">admin</span
          ><span v-else>user</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { mapActions, mapGetters } from "vuex";

export default {
  name: "Home",

  computed: {
    ...mapGetters(["getLoggedIn", "getUser"])
  },

  mounted() {
    if (localStorage.getItem("access_token")) {
      this.getUserData();
    }
  },

  methods: {
    ...mapActions(["getUserData"])
  }
};
</script>

// react-app/src/Home/Home.js
import React from "react";
import { Redirect } from "react-router-dom";

const Home = (props) => {
  if(!props.loggedIn) {
    return <Redirect to="/login" />;
  } else {
    return (
      <div className="container main_container">
        <div className="card">
          <div className="card-header">
            <strong>Home page</strong>
          </div>
          <div className="card-body text-center">
            Hi {props.user.name}, you are logged in!<br/>
          </div>
        </div>
      </div>
    );
  }
};

export default Home;
